# Generated by Django 5.0.3 on 2024-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('bakalavra', 'B'), ('magistratura', 'M'), ('professor', 'P')], default='bakalavra', max_length=20),
        ),
    ]
